@startuml "change agent mediator sequence"
autonumber
hide footbox

entity "Agents-R-Us (C)" as Charles
actor "Bob (B)" as Bob
entity "Agents-4-All (D)" as Delta
actor "Alice (A)" as Alice

== New Routing Record Setup ==

Bob -> Delta : { route-update-request }/B:D\nupdates[ (\n    recipient_key: B.verkey@B:A, action: create\n) ]
Delta -> Delta : routing-records[ D:B ] = [ B.verkey@A:B ]
Bob <-- Delta : { route-update-response }/D:B

== Advise Relying Parties ==

Bob -> Alice : DIDDoc( id: B.did@B:A,\n    recipientKeys: [B.verkey@B:A],\n    routingKeys: [<color blue>D.verkey@D:B</color>],\n    serviceEndpoint: <color blue>D.endpoint</color> )

... This is performed for all relying parties ...

== Existing Routing Record Removal ==

Bob -> Charles : { route-update-request }/B:C\nupdates[ (\n    recipient_key: B.verkey@B:A, action: <color green>delete</color>\n) ]
Bob <-- Charles : { route-update-response }/C:B

Alice -> Delta : All subsequent messages
Delta -> Bob : are forwarded through Agents-4-All

@enduml
