@startuml "connection sequence"
autonumber
hide footbox

actor "Alice (A)" as Alice
entity "Agents-R-Us (C)" as aru
actor "Bob (B)" as Bob

Bob <- Alice : { connection-invitation( recipientKeys: [A.invitation_key], serviceEndpoint: A.endpoint ) }

== Routing Record Setup ==

Bob -> aru : { route-update-request }/B:C\nupdates[ ( recipient_key: <color green>B.verkey@B:A</color>, action: <color green>create</color> ) ]
aru -> aru : routing-records[ C:B ] = [ B.verkey@A:B ]
Bob <-- aru : { route-update-response }/C:B

== Connection Request ==

Bob -> Alice :  { connection-request }/B:A\ndid_doc( id: B.did@B:A, recipientKeys: [<color green>B.verkey@B:A</color>],\n    routingKeys: [<color blue>C.verkey@C:B</color>], serviceEndpoint: <color blue>C.endpoint</color> )

== Connection Response ==

Alice -> Alice : pack { connection-response }/A:B\ndid_doc( id: A.did@A:B, recipientKeys: [A.verkey@A:B], serviceEndpoint: A.endpoint )
Alice -> aru : { forward( to: <color green>B.verkey@B:A</color> msg: connection-response ) }/A:C
aru -> aru : Look up routing\nrouting-records[ <color green>B.verkey@B:A</color> ] => C:B
Bob <- aru : { connection-response }/C:B

@enduml
